# fly.toml app configuration file generated for avikav-net on 2025-02-23T04:05:36-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'avikav-net'
primary_region = 'iad'
kill_signal = 'SIGTERM'

[build]

[env]
  DATABASE_PATH = '/litefs/avikav-net.db'
  PHX_HOST = 'avikav.net'
  PORT = '8081'

[[mounts]]
  source = 'name'
  destination = '/mnt/vol'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '1GB'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 10000
    soft_limit = 10000

[[vm]]
  size = 'shared-cpu-1x'
  memory = "512MB"
